//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineGrades.Core.Entity
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "User", Namespace = "http://schemas.datacontract.org/2004/07/onlineGrades.Core.Entity", IsReference = true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(onlineGrades.Core.Entity.Profesor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(onlineGrades.Core.Entity.Student))]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CetatenieField;

        private System.DateTime DataNasteriiField;

        private string EmailField;

        private string InitialaTataField;

        private string MamaField;

        private string NationalitateField;

        private string NumeField;

        private string PasswordField;

        private string PrenumeField;

        private System.Guid RegisterUUIDField;

        private System.Guid ResetUUIDField;

        private string TataField;

        private string UsernameField;

        private bool isActiveField;

        private System.Guid userIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cetatenie
        {
            get
            {
                return this.CetatenieField;
            }
            set
            {
                this.CetatenieField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNasterii
        {
            get
            {
                return this.DataNasteriiField;
            }
            set
            {
                this.DataNasteriiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InitialaTata
        {
            get
            {
                return this.InitialaTataField;
            }
            set
            {
                this.InitialaTataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mama
        {
            get
            {
                return this.MamaField;
            }
            set
            {
                this.MamaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationalitate
        {
            get
            {
                return this.NationalitateField;
            }
            set
            {
                this.NationalitateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RegisterUUID
        {
            get
            {
                return this.RegisterUUIDField;
            }
            set
            {
                this.RegisterUUIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ResetUUID
        {
            get
            {
                return this.ResetUUIDField;
            }
            set
            {
                this.ResetUUIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tata
        {
            get
            {
                return this.TataField;
            }
            set
            {
                this.TataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isActive
        {
            get
            {
                return this.isActiveField;
            }
            set
            {
                this.isActiveField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Profesor", Namespace = "http://schemas.datacontract.org/2004/07/onlineGrades.Core.Entity", IsReference = true)]
    public partial class Profesor : onlineGrades.Core.Entity.User
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Student", Namespace = "http://schemas.datacontract.org/2004/07/onlineGrades.Core.Entity", IsReference = true)]
    public partial class Student : onlineGrades.Core.Entity.User
    {

        private int AnUniversitarField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnUniversitar
        {
            get
            {
                return this.AnUniversitarField;
            }
            set
            {
                this.AnUniversitarField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IOnlineGradesWCF")]
public interface IOnlineGradesWCF
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOnlineGradesWCF/LoginUser", ReplyAction = "http://tempuri.org/IOnlineGradesWCF/LoginUserResponse")]
    onlineGrades.Core.Entity.User LoginUser(string username, string password);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOnlineGradesWCF/LoginUser", ReplyAction = "http://tempuri.org/IOnlineGradesWCF/LoginUserResponse")]
    System.Threading.Tasks.Task<onlineGrades.Core.Entity.User> LoginUserAsync(string username, string password);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOnlineGradesWCF/registerProfesor", ReplyAction = "http://tempuri.org/IOnlineGradesWCF/registerProfesorResponse")]
    bool registerProfesor(onlineGrades.Core.Entity.Profesor profesor);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOnlineGradesWCF/registerProfesor", ReplyAction = "http://tempuri.org/IOnlineGradesWCF/registerProfesorResponse")]
    System.Threading.Tasks.Task<bool> registerProfesorAsync(onlineGrades.Core.Entity.Profesor profesor);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOnlineGradesWCF/registerStudent", ReplyAction = "http://tempuri.org/IOnlineGradesWCF/registerStudentResponse")]
    bool registerStudent(onlineGrades.Core.Entity.Student student);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOnlineGradesWCF/registerStudent", ReplyAction = "http://tempuri.org/IOnlineGradesWCF/registerStudentResponse")]
    System.Threading.Tasks.Task<bool> registerStudentAsync(onlineGrades.Core.Entity.Student student);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOnlineGradesWCF/confirmUser", ReplyAction = "http://tempuri.org/IOnlineGradesWCF/confirmUserResponse")]
    bool confirmUser(System.Guid registerGuid);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOnlineGradesWCF/confirmUser", ReplyAction = "http://tempuri.org/IOnlineGradesWCF/confirmUserResponse")]
    System.Threading.Tasks.Task<bool> confirmUserAsync(System.Guid registerGuid);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOnlineGradesWCF/editProfesor", ReplyAction = "http://tempuri.org/IOnlineGradesWCF/editProfesorResponse")]
    bool editProfesor(onlineGrades.Core.Entity.Profesor profesor);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOnlineGradesWCF/editProfesor", ReplyAction = "http://tempuri.org/IOnlineGradesWCF/editProfesorResponse")]
    System.Threading.Tasks.Task<bool> editProfesorAsync(onlineGrades.Core.Entity.Profesor profesor);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOnlineGradesWCF/editStudent", ReplyAction = "http://tempuri.org/IOnlineGradesWCF/editStudentResponse")]
    bool editStudent(onlineGrades.Core.Entity.Student student);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOnlineGradesWCF/editStudent", ReplyAction = "http://tempuri.org/IOnlineGradesWCF/editStudentResponse")]
    System.Threading.Tasks.Task<bool> editStudentAsync(onlineGrades.Core.Entity.Student student);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IOnlineGradesWCFChannel : IOnlineGradesWCF, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class OnlineGradesWCFClient : System.ServiceModel.ClientBase<IOnlineGradesWCF>, IOnlineGradesWCF
{

    public OnlineGradesWCFClient()
    {
    }

    public OnlineGradesWCFClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public OnlineGradesWCFClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public OnlineGradesWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public OnlineGradesWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public onlineGrades.Core.Entity.User LoginUser(string username, string password)
    {
        return base.Channel.LoginUser(username, password);
    }

    public System.Threading.Tasks.Task<onlineGrades.Core.Entity.User> LoginUserAsync(string username, string password)
    {
        return base.Channel.LoginUserAsync(username, password);
    }

    public bool registerProfesor(onlineGrades.Core.Entity.Profesor profesor)
    {
        return base.Channel.registerProfesor(profesor);
    }

    public System.Threading.Tasks.Task<bool> registerProfesorAsync(onlineGrades.Core.Entity.Profesor profesor)
    {
        return base.Channel.registerProfesorAsync(profesor);
    }

    public bool registerStudent(onlineGrades.Core.Entity.Student student)
    {
        return base.Channel.registerStudent(student);
    }

    public System.Threading.Tasks.Task<bool> registerStudentAsync(onlineGrades.Core.Entity.Student student)
    {
        return base.Channel.registerStudentAsync(student);
    }

    public bool confirmUser(System.Guid registerGuid)
    {
        return base.Channel.confirmUser(registerGuid);
    }

    public System.Threading.Tasks.Task<bool> confirmUserAsync(System.Guid registerGuid)
    {
        return base.Channel.confirmUserAsync(registerGuid);
    }

    public bool editProfesor(onlineGrades.Core.Entity.Profesor profesor)
    {
        return base.Channel.editProfesor(profesor);
    }

    public System.Threading.Tasks.Task<bool> editProfesorAsync(onlineGrades.Core.Entity.Profesor profesor)
    {
        return base.Channel.editProfesorAsync(profesor);
    }

    public bool editStudent(onlineGrades.Core.Entity.Student student)
    {
        return base.Channel.editStudent(student);
    }

    public System.Threading.Tasks.Task<bool> editStudentAsync(onlineGrades.Core.Entity.Student student)
    {
        return base.Channel.editStudentAsync(student);
    }
}
